name:                category-theory-for-programmers
version:             0.1.0.0
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "2019 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/category-theory-for-programmers#readme>

default-extensions:
- PolyKinds
- TypeFamilies

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  category-theory-for-programmers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-theory-for-programmers

tests:
  category-theory-for-programmers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-theory-for-programmers
